# Ezarcher custom settings
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the bootloader module.
# 
---

# Define which bootloader you want to use for EFI installations
efiBootLoader: "grub"

# kernelSearchPath is the path relative to the root of the install to search for kernels
kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"

# loaderEntries is an array of options to add to loader.conf for systemd-boot
loaderEntries:
  - "timeout 5"
  - "console-mode keep"
  
# systemd-boot and refind support custom kernel params
kernelParams: [ "quiet" ]

# A list of kernel names that refind should accept as kernels
#refindKernelList: [ "linux","linux-lts","linux-zen","linux-hardened" ]

# Optionally set the bootloader ID to use for EFI
efiBootloaderId: "ezarcher"

# GRUB 2 binary names and boot directory
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

# Optionally install a copy of the GRUB EFI bootloader as the EFI fallback loader
installEFIFallback: true

# Optionally install both BIOS and UEFI GRUB bootloaders
installHybridGRUB: false

