# Ezarcher custom settings
# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the shellprocess-fixmkinitcpio.conf file.
#
---

i18n:
    name: "Fix mkinitcpio stuff"

# Copy correct mkinitcpio files for installed system
dontChroot: false
timeout: 999
script:
    - "-mv ${ROOT}etc/ezmkinitcpio.conf ${ROOT}etc/mkinitcpio.conf"
    - "-mv ${ROOT}etc/mkinitcpio.d/ezmkinit ${ROOT}etc/mkinitcpio.d/linux-lts.preset"
    - "-rm ${ROOT}etc/mkinitcpio.conf.d/archiso.conf

