[Autologin]
User=live
Session=plasma
Relogin=false

[General]
HaltCommand=/usr/bin/systemctl poweroff
InputMethod=qtvirtualkeyboard
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=silent-nyarch

[Users]
MaximumUid=60513
MinimumUid=1000
